### ISSUE TITLE
[Bug]: Error: Unknown option 'internalModule'

### ISSUE THREAD

**Issue by chasingmaxwell** [lorisleiva/typedoc-plugin-expand-object-like-types#1]
Received this error when trying to compile docs after installing version 0.1.1:

```
Error: Unknown option 'internalModule'
```

If I install version 0.1.0 the error goes away and I can successfully use the plugin.

**Comment by TomChamberlainUK** [comment]
Also getting the same issue:
```
TypeDoc exiting with unexpected error:
Error: Unknown option 'internalModule'
```

**Comment by lorisleiva** [comment]
Thanks for raising this.

It was due to the fact that I always use this package with the `typedoc-plugin-missing-exports` which contains the `internalModule` option.

Version `0.1.2` fixes this by checking that the option exists first.
